
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 200
  database: app
  username: root
  password: password
  host: db
  port: 3306
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  